version: "3.5"
services:
  cache:
    image: robrt/jolt-cache:latest
    environment:
      - JOLT_INSECURE=true
      - JOLT_MAX_SIZE=10GB
      - JOLT_VERBOSITY=2
    ports:
      - "8080:8080"
    volumes:
      - cache-http:/data
  dashboard:
    image: robrt/jolt-dashboard:latest
    ports:
      - "80:80"
  scheduler:
    image: robrt/jolt-scheduler:latest
    ports:
      - "9090:9090"
  worker:
    environment:
      - "JOLT_CACHE_URL=http://cache"
    image: robrt/jolt-worker:latest
    deploy:
      replicas: 2
    configs:
      - source: worker.conf
        target: /root/.config/jolt/config
    volumes:
      - cache-node:/root/.cache/jolt
configs:
  worker.conf:
    file: ./worker.conf
  nginx.conf:
    file: ./nginx.conf
volumes:
  cache-node:
  cache-http:
