version: "3.5"
services:
  amqp:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
  cache:
    image: robrt/jolt-cache:latest
    environment:
      - JOLT_INSECURE=true
      - JOLT_MAX_SIZE=10GB
      - JOLT_VERBOSITY=2
    ports:
      - "8080:8080"
    volumes:
      - cache-http:/data
  dashboard:
    image: robrt/jolt-dashboard:latest
    ports:
      - "80:80"
  worker:
    image: robrt/jolt:latest
    deploy:
      replicas: 2
    command: ["-c", "/opt/jolt/worker.conf", "amqp-worker"]
    configs:
      - source: worker-amqp.conf
        target: /opt/jolt/worker.conf
    environment:
      - "JOLT_CACHE_URL=http://cache"
    volumes:
      - cache-node:/root/.cache/jolt
configs:
  worker-amqp.conf:
    file: ./worker-amqp.conf
  nginx.conf:
    file: ./nginx.conf
volumes:
  cache-node:
  cache-http:
